<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>cyclo_cumotion_object_attachment</name>
  <version>0.1.0</version>
  <description>Predefined-object integration for Isaac ROS cuMotion attachment.</description>

  <maintainer email="pyo@robotis.com">Pyo</maintainer>
  <license>Apache 2.0</license>

  <url type="repository">https://github.com/ROBOTIS-GIT/cyclo_solution</url>

  <author email="kyu@robotis.com">Yeonguk Kim</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>isaac_ros_cumotion_interfaces</exec_depend>
  <exec_depend>isaac_ros_cumotion_object_attachment</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>robotis_interfaces</exec_depend>
  <exec_depend>std_srvs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
